name: "Test publish"
on:
  workflow_call:
    secrets:
      ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME:
        required: true
      ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD:
        required: true
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY:
        required: true
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID:
        required: true
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD:
        required: true

jobs:
  publish:
    name: "Try publish local"
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Run publish
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :build-logic:plugins:android:publishAllPublicationsToMavenCentralRepository :build-logic:plugins:convention:publishAllPublicationsToMavenCentralRepository :build-logic:plugins:minecraft:publishAllPublicationsToMavenCentralRepository --stacktrace
  release:
    needs: [ publish ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # steps.properties.outputs.project-version-string
      # steps.properties.outputs.project-name
      - uses: christian-draeger/read-properties@1.1.1
        id: properties
        with:
          path: './build-logic/gradle.properties'
          properties: 'project.name project.version.string'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ steps.properties.outputs.project-version-string }}
          name: ${{ steps.properties.outputs.project-name }} - ${{ steps.properties.outputs.project-version-string }}
          draft: false
          prerelease: false